version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8800:80"
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: larablog_test
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8200:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

  phpmyadmin:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    container_name: project_phpmyadmin
